#!/usr/bin/env python3
"""
Prepare Complex PDB Files for MD Simulation
============================================

Combines receptor (PDBQT) with docked ligands (SDF) to create
complex PDB files ready for OpenMM simulation.

Input:
- human_NOD2_LRR.pdbqt (receptor)
- *_docked.sdf (ligands with docked poses)

Output:
- complex_*.pdb (receptor + ligand complexes)
- receptor.pdb (clean receptor PDB)
- ligand_*.pdb (individual ligand PDBs)
"""

import os
import sys
from pathlib import Path
from datetime import datetime

# RDKit for SDF processing
try:
    from rdkit import Chem
    from rdkit.Chem import AllChem
    RDKIT_AVAILABLE = True
except ImportError:
    RDKIT_AVAILABLE = False
    print("WARNING: RDKit not available. Using basic conversion.")

# Directories
BASE_DIR = Path(__file__).parent.parent
STRUCTURES_DIR = BASE_DIR / "md_simulation" / "structures"

# Input files
RECEPTOR_PDBQT = STRUCTURES_DIR / "human_NOD2_LRR.pdbqt"

LIGANDS = {
    'febuxostat': STRUCTURES_DIR / "febuxostat_docked.sdf",
    'ursodiol': STRUCTURES_DIR / "ursodiol_docked.sdf",
    'budesonide': STRUCTURES_DIR / "budesonide_docked.sdf",
    'decoy': STRUCTURES_DIR / "decoy_docked.sdf",
}


def pdbqt_to_pdb(pdbqt_file: Path, pdb_file: Path) -> bool:
    """
    Convert PDBQT to PDB by removing AutoDock-specific columns.
    Keeps only standard PDB columns.
    """
    print(f"Converting {pdbqt_file.name} to PDB...")

    try:
        with open(pdbqt_file, 'r') as f_in, open(pdb_file, 'w') as f_out:
            # Write header
            f_out.write(f"REMARK   Generated by NOD2-Scout prepare_complexes.py\n")
            f_out.write(f"REMARK   Source: {pdbqt_file.name}\n")
            f_out.write(f"REMARK   Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")

            for line in f_in:
                if line.startswith('ATOM') or line.startswith('HETATM'):
                    # PDBQT format: columns 1-66 are standard PDB, rest is AutoDock data
                    # Standard PDB ATOM record is 80 chars, but we only need first 66
                    pdb_line = line[:66].rstrip()

                    # Ensure proper line length (pad if needed)
                    if len(pdb_line) < 66:
                        pdb_line = pdb_line.ljust(66)

                    f_out.write(pdb_line + '\n')

                elif line.startswith('TER') or line.startswith('END'):
                    f_out.write(line.strip() + '\n')

            f_out.write('END\n')

        print(f"  Created: {pdb_file.name}")
        return True

    except Exception as e:
        print(f"  ERROR: {e}")
        return False


def sdf_to_pdb(sdf_file: Path, pdb_file: Path, ligand_name: str = 'LIG') -> bool:
    """
    Convert SDF to PDB format.
    Uses RDKit if available, otherwise basic conversion.
    """
    print(f"Converting {sdf_file.name} to PDB...")

    if RDKIT_AVAILABLE:
        try:
            # Read SDF - get first (best) conformer
            suppl = Chem.SDMolSupplier(str(sdf_file), removeHs=False)
            mol = next(suppl)

            if mol is None:
                print(f"  ERROR: Could not read molecule from {sdf_file.name}")
                return False

            # Set residue name
            for atom in mol.GetAtoms():
                mi = Chem.AtomPDBResidueInfo()
                mi.SetResidueName(ligand_name.upper()[:3])
                mi.SetResidueNumber(1)
                mi.SetChainId('L')
                mi.SetName(f" {atom.GetSymbol()}{atom.GetIdx()+1:2d} ")
                mi.SetIsHeteroAtom(True)
                atom.SetPDBResidueInfo(mi)

            # Write PDB
            Chem.MolToPDBFile(mol, str(pdb_file))

            print(f"  Created: {pdb_file.name} ({mol.GetNumAtoms()} atoms)")
            return True

        except Exception as e:
            print(f"  ERROR with RDKit: {e}")
            print("  Falling back to basic conversion...")

    # Basic conversion without RDKit
    return sdf_to_pdb_basic(sdf_file, pdb_file, ligand_name)


def sdf_to_pdb_basic(sdf_file: Path, pdb_file: Path, ligand_name: str = 'LIG') -> bool:
    """
    Basic SDF to PDB conversion without RDKit.
    Reads atom coordinates from SDF and writes minimal PDB.
    """
    try:
        with open(sdf_file, 'r') as f:
            lines = f.readlines()

        # Parse SDF header
        # Line 4 contains atom/bond count
        counts_line = lines[3].split()
        n_atoms = int(counts_line[0])

        # Atom block starts at line 4 (0-indexed)
        atoms = []
        for i in range(4, 4 + n_atoms):
            parts = lines[i].split()
            x, y, z = float(parts[0]), float(parts[1]), float(parts[2])
            element = parts[3]
            atoms.append((element, x, y, z))

        # Write PDB
        with open(pdb_file, 'w') as f:
            f.write(f"REMARK   Ligand: {ligand_name}\n")
            f.write(f"REMARK   Source: {sdf_file.name}\n")

            for i, (element, x, y, z) in enumerate(atoms):
                atom_name = f"{element}{i+1:2d}".center(4)
                f.write(f"HETATM{i+1:5d} {atom_name} LIG L   1    "
                       f"{x:8.3f}{y:8.3f}{z:8.3f}  1.00  0.00          {element:>2}\n")

            f.write("END\n")

        print(f"  Created: {pdb_file.name} ({n_atoms} atoms)")
        return True

    except Exception as e:
        print(f"  ERROR: {e}")
        return False


def create_complex(receptor_pdb: Path, ligand_pdb: Path, complex_pdb: Path,
                   ligand_name: str) -> bool:
    """
    Combine receptor and ligand PDBs into a complex.
    """
    print(f"Creating complex: {complex_pdb.name}")

    try:
        with open(complex_pdb, 'w') as f_out:
            # Header
            f_out.write(f"REMARK   NOD2-Scout MD Complex\n")
            f_out.write(f"REMARK   Receptor: {receptor_pdb.name}\n")
            f_out.write(f"REMARK   Ligand: {ligand_name}\n")
            f_out.write(f"REMARK   Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")

            # Write receptor (skip header lines and END)
            with open(receptor_pdb, 'r') as f_rec:
                for line in f_rec:
                    if line.startswith('ATOM'):
                        f_out.write(line)

            # Add TER between receptor and ligand
            f_out.write("TER\n")

            # Write ligand (skip header lines and END)
            with open(ligand_pdb, 'r') as f_lig:
                for line in f_lig:
                    if line.startswith('HETATM') or line.startswith('ATOM'):
                        f_out.write(line)

            f_out.write("TER\n")
            f_out.write("END\n")

        # Count atoms
        n_atoms = sum(1 for line in open(complex_pdb)
                     if line.startswith('ATOM') or line.startswith('HETATM'))
        print(f"  Created: {complex_pdb.name} ({n_atoms} total atoms)")
        return True

    except Exception as e:
        print(f"  ERROR: {e}")
        return False


def create_apo_structure(receptor_pdb: Path, apo_pdb: Path) -> bool:
    """
    Create apo (ligand-free) structure for negative control.
    """
    print(f"Creating apo structure: {apo_pdb.name}")

    try:
        with open(apo_pdb, 'w') as f_out:
            f_out.write(f"REMARK   NOD2-Scout MD Apo Structure (Negative Control)\n")
            f_out.write(f"REMARK   Source: {receptor_pdb.name}\n")
            f_out.write(f"REMARK   Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")

            with open(receptor_pdb, 'r') as f_rec:
                for line in f_rec:
                    if line.startswith('ATOM') or line.startswith('TER') or line.startswith('END'):
                        f_out.write(line)

        print(f"  Created: {apo_pdb.name}")
        return True

    except Exception as e:
        print(f"  ERROR: {e}")
        return False


def main():
    """Main execution"""
    print("=" * 60)
    print("PREPARING COMPLEX STRUCTURES FOR MD SIMULATION")
    print("=" * 60)
    print(f"\nTimestamp: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print(f"RDKit available: {RDKIT_AVAILABLE}")
    print(f"Structures directory: {STRUCTURES_DIR}")
    print()

    # Check input files exist
    print("Checking input files...")
    if not RECEPTOR_PDBQT.exists():
        print(f"  ERROR: Receptor not found: {RECEPTOR_PDBQT}")
        sys.exit(1)
    print(f"  Receptor: {RECEPTOR_PDBQT.name} ({RECEPTOR_PDBQT.stat().st_size:,} bytes)")

    for name, path in LIGANDS.items():
        if path.exists():
            print(f"  {name}: {path.name} ({path.stat().st_size:,} bytes)")
        else:
            print(f"  {name}: NOT FOUND - {path.name}")
    print()

    # Step 1: Convert receptor PDBQT to PDB
    print("-" * 40)
    print("STEP 1: Convert Receptor")
    print("-" * 40)
    receptor_pdb = STRUCTURES_DIR / "receptor.pdb"
    if not pdbqt_to_pdb(RECEPTOR_PDBQT, receptor_pdb):
        print("ERROR: Failed to convert receptor")
        sys.exit(1)
    print()

    # Step 2: Convert ligands SDF to PDB
    print("-" * 40)
    print("STEP 2: Convert Ligands")
    print("-" * 40)
    ligand_pdbs = {}
    for name, sdf_path in LIGANDS.items():
        if sdf_path.exists():
            ligand_pdb = STRUCTURES_DIR / f"ligand_{name}.pdb"
            if sdf_to_pdb(sdf_path, ligand_pdb, name.upper()[:3]):
                ligand_pdbs[name] = ligand_pdb
    print()

    # Step 3: Create complexes
    print("-" * 40)
    print("STEP 3: Create Complexes")
    print("-" * 40)
    complexes_created = []
    for name, ligand_pdb in ligand_pdbs.items():
        complex_pdb = STRUCTURES_DIR / f"complex_{name}.pdb"
        if create_complex(receptor_pdb, ligand_pdb, complex_pdb, name):
            complexes_created.append(complex_pdb)
    print()

    # Step 4: Create apo structure
    print("-" * 40)
    print("STEP 4: Create Apo Structure")
    print("-" * 40)
    apo_pdb = STRUCTURES_DIR / "complex_apo.pdb"
    create_apo_structure(receptor_pdb, apo_pdb)
    print()

    # Summary
    print("=" * 60)
    print("SUMMARY")
    print("=" * 60)
    print(f"\nFiles created in {STRUCTURES_DIR}:\n")

    for f in sorted(STRUCTURES_DIR.glob("*.pdb")):
        size = f.stat().st_size
        print(f"  {f.name:30} {size:>10,} bytes")

    print(f"\n{'=' * 60}")
    print("READY FOR MD SIMULATION")
    print("=" * 60)
    print("""
Next steps:
1. Upload to GPU instance:
   scp -r md_simulation/structures/ user@gpu:~/nod2/
   scp -r md_simulation/gpu_scripts/ user@gpu:~/nod2/

2. On GPU, run:
   cd ~/nod2
   ./gpu_scripts/master_md_pipeline.sh

Or run individual simulations:
   python gpu_scripts/03_run_md_febuxostat.py --pdb structures/complex_febuxostat.pdb
""")


if __name__ == "__main__":
    main()
